---
  - name: print-secret
    hosts: servers
    become: yes
    vars_files:
      - secret-password.yaml
    tasks:
      - name: print-secrets
        debug:
          msg: "this is the secret-name {{my_name}}"
